name: Docker build & push😎


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login docker.pkg.github.com -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - name: docker build python
      run: |
        docker build ./action-a -t docker.pkg.github.com/alexandernurzhanov/hello-github-actions/python:1.0.3
    - name: docker push
      run: |
        docker push docker.pkg.github.com/alexandernurzhanov/hello-github-actions/python:1.0.3