name: My first GitHub Actions-Repo
on: push
jobs:
  build:
    name: My first Action!😎
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Alex"
