name: Docker Series Builds


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - name: docker build python
      run: |
        docker build ./action-a -t python:test
    - name: docker push
      run: |
        docker push python:test